openapi: 3.0.1
info:
  title: ResearchGroupVision
  description: API Definition of ResearchGroupVision
  version: 1.0.0
servers:
- url: http://localhost:8290/research-group/v1/vision/
- url: https://localhost:8253/research-group/v1/vision/
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /publications:
    get:
      responses:
        default:
          description: Default response
